# https://github.com/GoogleCloudPlatform/professional-services/blob/main/examples/dbt-on-cloud-composer/optimized/dbt-project/.dbt/profiles.yml

steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Pull docker cache
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/dbt-builder-basic:latest || exit 0

- name: gcr.io/cloud-builders/docker
  id: Build Airflow DAGs Builder
  args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/dbt-builder-basic',
      '--cache-from', 'gcr.io/$PROJECT_ID/dbt-builder-basic:latest',
      './'
    ]

- name: gcr.io/cloud-builders/docker
  id: Push Airflow DAGs Builder
  args: [
      'push',
      'gcr.io/$PROJECT_ID/dbt-builder-basic:latest'
    ]

# # Generate dbt documentation
# - name: 'gcr.io/$PROJECT_ID/airflow-dags-builder'
#   id: Generate documentation
#   entrypoint: bash
#   args:
#   - -c
#   - |
#     dbt docs generate --vars '{"project_id": "final-project-team1","bigquery_location": "us","impersonate_service_account": ${_DBT_SERVICE_ACCOUNT},"execution_date": "1970-01-01","source_data_project": "time_stamp_fraud_complete"}' --profiles-dir .dbt --target cloud-build
# _GCS_BUCKET is the GCS Bucket that will store the dbt documentation
- name: gcr.io/cloud-builders/gsutil
  id: Copy the target to GCS
  args:
  - -m
  - rsync
  - -r
  - -c
  - -x
  - .dockerignore|key|logs|models|tests|.dockerignore|.gitignore|cloudbuild.yaml|Dockerfile|README.md|.git
  - .
  - gs://${_GCS_BUCKET}/data/dbt-docs-optimized/

options:
  logging: CLOUD_LOGGING_ONLY